import { marked } from 'marked';
import puppeteer, { Browser } from 'puppeteer';

/**
 * Markdown → typeset A4 PDF via one shared headless Chromium.
 * The template owns the looks; the agent's markdown owns the content.
 */
let browserPromise: Promise<Browser> | null = null;

function getBrowser(): Promise<Browser> {
  return (browserPromise ??= puppeteer.launch({
    headless: true,
    // In the Docker image chromium comes from apt (PUPPETEER_EXECUTABLE_PATH);
    // locally puppeteer's own download is used.
    executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
    args: ['--no-sandbox', '--disable-dev-shm-usage'],
  }));
}

export async function closeBrowser(): Promise<void> {
  if (browserPromise) {
    const b = await browserPromise;
    browserPromise = null;
    await b.close();
  }
}

const CSS = `
  * { box-sizing: border-box; }
  body { font-family: Georgia, 'Times New Roman', serif; color: #1c1c1e; margin: 0; font-size: 11pt; line-height: 1.65; }
  .cover { border-bottom: 3px solid #4f46e5; padding: 0 0 18px; margin-bottom: 28px; }
  .cover h1 { font-size: 24pt; line-height: 1.25; margin: 0 0 10px; }
  .cover .meta { font-family: 'Segoe UI', system-ui, sans-serif; font-size: 9pt; color: #6b7280; }
  h1, h2, h3 { font-family: 'Segoe UI', system-ui, sans-serif; color: #111; line-height: 1.3; }
  h1 { font-size: 16pt; margin: 26px 0 10px; }
  h2 { font-size: 13.5pt; margin: 22px 0 8px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
  h3 { font-size: 11.5pt; margin: 18px 0 6px; }
  p { margin: 8px 0; text-align: justify; }
  a { color: #4338ca; text-decoration: none; }
  ul, ol { margin: 8px 0; padding-left: 22px; }
  li { margin: 4px 0; }
  blockquote { border-left: 3px solid #c7d2fe; margin: 12px 0; padding: 2px 0 2px 14px; color: #4b5563; font-style: italic; }
  code { font-family: Consolas, monospace; font-size: 9.5pt; background: #f3f4f6; padding: 1px 4px; border-radius: 3px; }
  pre { background: #f3f4f6; border: 1px solid #e5e7eb; border-radius: 6px; padding: 10px 12px; overflow-x: hidden; white-space: pre-wrap; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 10pt; font-family: 'Segoe UI', system-ui, sans-serif; }
  th, td { border: 1px solid #d1d5db; padding: 6px 9px; text-align: left; }
  th { background: #eef2ff; }
  hr { border: none; border-top: 1px solid #e5e7eb; margin: 20px 0; }
`;

export async function renderPdf(title: string, contentMd: string): Promise<Buffer> {
  const bodyHtml = await marked.parse(contentMd, { async: true });
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const html = `<!doctype html><html><head><meta charset="utf-8"><style>${CSS}</style></head>
<body>
  <div class="cover">
    <h1>${escapeHtml(title)}</h1>
    <p class="meta">${date} · Generated by MicroManus deep research</p>
  </div>
  ${bodyHtml}
</body></html>`;

  const browser = await getBrowser();
  const page = await browser.newPage();
  try {
    await page.setContent(html, { waitUntil: 'load' });
    const pdf = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '18mm', bottom: '18mm', left: '17mm', right: '17mm' },
      displayHeaderFooter: true,
      headerTemplate: '<span></span>',
      footerTemplate: `<div style="width:100%;font-size:8px;color:#9ca3af;text-align:center;font-family:sans-serif;">
        <span class="pageNumber"></span> / <span class="totalPages"></span></div>`,
    });
    return Buffer.from(pdf);
  } finally {
    await page.close();
  }
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
